services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    Pintushi\Bundle\SecurityBundle\ORM\Walker\AclHelper:
        class: 'Pintushi\Bundle\SecurityBundle\ORM\Walker\AclHelper'
        arguments:
             - '@service_container'

    pintushi_security.acl_helper:
        alias:  'Pintushi\Bundle\SecurityBundle\ORM\Walker\AclHelper'

    pintushi_security.orm.ownership_sql_walker_builder:
        public: false
        class: 'Pintushi\Bundle\SecurityBundle\ORM\Walker\OwnershipConditionDataBuilder'
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@pintushi_security.acl.object_id_accessor'
            - '@pintushi_security.entity_security_metadata_provider'
            - '@pintushi_security.owner.ownership_metadata_provider.chain'
            - '@pintushi_security.ownership_tree_provider.chain'
            - '@pintushi.acl.voter.basic_permissions'
        calls:
            - [setAclGroupProvider, ['@pintushi_security.acl.group_provider.chain']]

    Pintushi\Bundle\SecurityBundle\ORM\Walker\CurrentUserWalkerHintProvider:
        arguments:
             - '@pintushi_security.token_accessor'

    pintushi_security.walker_hint_provider.current_user: '@Pintushi\Bundle\SecurityBundle\ORM\Walker\CurrentUserWalkerHintProvider'

    pintushi_security.query_hint.filter_by_current_user:
        public: false
        abstract: true
        tags:
            -
                name: pintushi_security.query_hint
                hint: pintushi_security.filter_by_current_user
                alias: HINT_FILTER_BY_CURRENT_USER
                tree_walker: Pintushi\Bundle\SecurityBundle\ORM\Walker\CurrentUserWalker
                walker_hint_provider: pintushi_security.walker_hint_provider.current_user

    pintushi_security.access_rule.chain_access_rule:
        class: Pintushi\Bundle\SecurityBundle\AccessRule\ChainAccessRule

    pintushi_security.access_rule.acl:
        class: Pintushi\Bundle\SecurityBundle\AccessRule\AclAccessRule
        arguments:
            - '@pintushi_security.orm.ownership_sql_walker_builder'
            - '@pintushi_security.owner.ownership_metadata_provider.chain'
        tags:
            - { name: pintushi_security.access_rule }

    pintushi_security.access_rule.available_owner_check:
        class: Pintushi\Bundle\SecurityBundle\AccessRule\AvailableOwnerAccessRule
        arguments:
            - '@pintushi_security.orm.ownership_sql_walker_builder'
            - '@pintushi_security.owner.ownership_metadata_provider.chain'
        tags:
            - { name: pintushi_security.access_rule }
