imports:
    - { resource: permission_configuration.yml }
    - { resource: acl.yml }
    - { resource: ownership.yml }
    - { resource: acl_walker.yml }
    - { resource: privilege.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\SecurityBundle\:
        resource: '../../{Repository,DataFixtures,Controller,Command,Authorization,ORM/{DoctrineHelper.php,EntityClassResolver.php}}'

    pintushi_security.authorization_checker:
        class: Pintushi\Bundle\SecurityBundle\Authorization\AuthorizationChecker
        decorates: 'security.authorization_checker'
        public: false
        autowire: false
        autoconfigure: false
        arguments:
            - '@pintushi_security.authorization_checker.inner'
            - '@pintushi_security.acl.object_identity_factory'
            - '@pintushi_security.acl.annotation_provider'
            - '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'security'}

    pintushi_security.class_authorization_checker:
        class: Pintushi\Bundle\SecurityBundle\Authorization\ClassAuthorizationChecker
        arguments:
            - '@pintushi_security.authorization_checker'
            - '@pintushi_security.acl.object_identity_factory'
            - '@pintushi_security.acl.annotation_provider'
            - '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'security'}

    pintushi_security.acl.configurable_permission_provider:
        class: Pintushi\Bundle\SecurityBundle\Acl\Permission\ConfigurablePermissionProvider
        arguments:
            - '@pintushi_security.configuration.provider.configurable_permission_configuration'
            - '@pintushi_security.cache.provider.configurable_permission'

    pintushi_security.cache.provider.configurable_permission:
        public: false
        autowire: false
        autoconfigure: false
        parent: doctrine_cache.abstract.chain
        calls:
            - [ setNamespace, [ 'pintushi_security_configurable_permission' ] ]

    pintushi.security.guard.jwt_token_authenticator:
        class: Pintushi\Bundle\SecurityBundle\Security\Guard\JWTTokenAuthenticator
        arguments:
            - "@lexik_jwt_authentication.jwt_manager"
            - "@event_dispatcher"
            - "@lexik_jwt_authentication.extractor.chain_extractor"

    Pintushi\Bundle\SecurityBundle\Form\FieldAclHelper: ~

    Pintushi\Bundle\SecurityBundle\Form\Extension\AclProtectedTypeExtension:
        tags:
            - { name: 'form.type_extension', extended_type: 'Symfony\Bridge\Doctrine\Form\Type\EntityType' }

    Pintushi\Bundle\SecurityBundle\Form\Extension\AclProtectedFieldTypeExtension:
        tags:
            - { name: 'form.type_extension', extended_type: 'Symfony\Component\Form\Extension\Core\Type\FormType' }

    Pintushi\Bundle\SecurityBundle\Authorization\RequestAuthorizationChecker: ~

    Pintushi\Bundle\SecurityBundle\Request\ParamConverter\DoctrineParamConverter:
        autowire: false
        autoconfigure: false
        public: false
        decorates: 'sensio_framework_extra.converter.doctrine.orm'
        parent: 'sensio_framework_extra.converter.doctrine.orm'
        arguments:
            - []
            - '@Pintushi\Bundle\SecurityBundle\Authorization\RequestAuthorizationChecker'

    Pintushi\Bundle\SecurityBundle\Helper\GrantedInfoHelper:
        arguments:
            - '@pintushi.acl.voter.basic_permissions'
            - '@pintushi_security.authorization_checker'
            - '@pintushi_security.token_accessor'

